var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),n=!1,ha;function ia(){var a=h.preRun;a&&(typeof a=="function"&&(a=[a]),ja.push(...a));for(a=ja;a.length>0;)a.shift()(h)}
function ka(){var a=h.postRun;a&&(typeof a=="function"&&(a=[a]),la.push(...a));for(a=la;a.length>0;)a.shift()(h)}function ma(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);n=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var na;async function oa(a){try{var b=await ea(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";}
async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}async function qa(a){var b=na;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return pa(b,a)}class ra{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var la=[],ja=[],sa=!0,ta=globalThis.TextDecoder&&new TextDecoder,p=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(d-b>16&&a.buffer&&ta)return ta.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if((e&224)==192)c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=(e&240)==224?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;e<65536?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
q,ua,va=a=>{if(!(a instanceof ra||a=="unwind"))throw a;},wa=a=>{ha=a;sa||(h.onExit?.(a),n=!0);throw new ra(a);},xa=()=>{if(!sa)try{var a=ha;ha=a;wa(a)}catch(b){va(b)}},r,u,ya=!1,za=[];function Aa(){function a(){ya=document.pointerLockElement===h.canvas}if(!Ba){Ba=!0;var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a),h.elementPointerLock&&b.addEventListener("click",c=>{!ya&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())}))}}
function Ca(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var g={antialias:!1,alpha:!1,bf:1};if(d)for(var f in d)g[f]=d[f];if(typeof Da!="undefined"&&(e=Ea(a,g)))var l=v[e].se}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&Fa(e),za.forEach(m=>m()),Aa());return l}
var Ba,w=12288,Ga=!1,Ha=0,Ia=0,Ja=0,x={alpha:!1,depth:!1,stencil:!1,antialias:!1},Ka={},y,z,La=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,f)=>b.drawElementsInstancedANGLE(c,d,e,g,f))},Ma=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Na=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Oa=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},Pa=1,A=[],C=[],D=[],E=[],F=[],G=[],Qa=[],v=[],H=[],Ra={},Sa=4,Ta=0,Va=a=>{for(var b=Pa++,c=a.length;c<b;c++)a[c]=null;return b},Wa=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=z[c](),f=g&&Va(d);g?(g.name=f,d[f]=g):J||=1282;r[b+e*4>>2]=f}},Ea=(a,b)=>{a.he||(a.he=a.getContext,a.getContext=function(d,e){e=a.he(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Xa(c,b):0},Xa=(a,b)=>{var c=
Va(v),d={handle:c,attributes:b,version:b.bf,se:a};a.canvas&&(a.canvas.we=d);v[c]=d;if(typeof b.nf=="undefined"||b.nf)if((a=d)||(a=Ya),!a.tf){a.tf=!0;a=a.se;a.If=a.getExtension("WEBGL_multi_draw");a.qf=a.getExtension("EXT_polygon_offset_clamp");a.pf=a.getExtension("EXT_clip_control");a.xf=a.getExtension("WEBGL_polygon_mode");La(a);Ma(a);Na(a);a.re=a.getExtension("EXT_disjoint_timer_query");for(var e of Oa(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},Fa=a=>{Ya=v[a];
h.ctx=z=Ya?.se},Da={},J,Ya,Za=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},K=(a,b,c)=>{var d=q;if(!(c>0))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);if(f<=127){if(b>=c)break;d[b++]=f}else if(f<=2047){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(f<=65535){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&
63;d[b++]=128|f>>6&63;d[b++]=128|f&63;g++}}d[b]=0;return b-e},N=a=>{var b=Za(a)+1,c=M(b);c&&K(a,c,b);return c},nb=(a,b,c,d,e)=>{function g(){return f<$a?(xa(),!1):!0}ab=a;bb=d;var f=$a;cb=function(){if(!n)if(db.length>0){var l=db.shift();l.Ff(l.yf);if(eb){var m=eb,t=m%1==0?m-1:Math.floor(m);eb=l.Bf?t:(8*m+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",m=eb??0,t=fb.Ef??0,m?m<t?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));g()&&setTimeout(cb,
0)}else if(g())if(gb=gb+1|0,hb==1&&ib>1&&gb%ib!=0)O();else{hb==0&&(jb=performance.now());a:if(!n){for(l of kb)if(l()===!1)break a;if(!n)try{a()}catch(B){va(B)}finally{xa()}for(m of lb)m()}g()&&O()}};e||(b>0?mb(0,1E3/b):mb(1,1),O());if(c)throw"unwind";},ab=null,O=null,$a=0,bb=0,hb=0,ib=0,gb=0,db=[],kb=[],lb=[],ob=0;function pb(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(ob)for(;b+2>=ob;)ob+=1E3/60;else ob=b+1E3/60;setTimeout(a,Math.max(ob-b,0))}}
var fb={},cb,eb,jb,qb,mb=(a,b)=>{hb=a;ib=b;if(ab)if(a==0)O=function(){setTimeout(cb,Math.max(0,jb+b-performance.now())|0)};else if(a==1)O=function(){pb(cb)};else{if(!qb)if(globalThis.scheduler)qb=scheduler.postTask.bind(scheduler);else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);qb=d=>{c.push(d);postMessage("setimmediate","*")}}O=function(){qb(cb)}}},rb=[],P,sb=(a,b)=>{rb.length=0;for(var c;c=q[a++];){var d=c!=105;d&=c!=112;b+=d&&b%8?4:0;
rb.push(c==112?u[b>>2]:c==106?ua[b>>3]:c==105?r[b>>2]:P[b>>3]);b+=d?8:4}return rb};function tb(a){var b=Q.ke[a];b.target.removeEventListener(b.ie,b.$e,b.me);Q.ke.splice(a,1)}function ub(a,b,c){function d(g,f){if(g.length!=f.length)return!1;for(var l=0;l<g.length;l++)if(g[l]!=f[l])return!1;return!0}for(var e of Q.te)if(e.Se==a&&d(e.Ye,c))return;Q.te.push({Se:a,df:b,Ye:c});Q.te.sort((g,f)=>g.df-f.df)}function vb(a){Q.te=Q.te.filter(b=>b.Se!=a)}
function wb(){return navigator.userActivation?navigator.userActivation.isActive:Q.Ne&&Q.hf.ze}function xb(){if(wb()){var a=Q.te;Q.te=[];for(var b of a)b.Se(...b.Ye)}}function R(a){if(!a.target)return-4;if(a.je)a.$e=function(c){++Q.Ne;Q.hf=a;xb();a.oe(c);xb();--Q.Ne},a.target.addEventListener(a.ie,a.$e,a.me),Q.ke.push(a);else for(var b=0;b<Q.ke.length;++b)Q.ke[b].target==a.target&&Q.ke[b].ie==a.ie&&tb(b--);return 0}function yb(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var Q={zf:0,Me:0,Oe:0,He:0,Xe:0,Ue:0,Ke:0,Df:0,Jf:0,Cf:0,Le:0,Qe:0,We:0,Te:0,Kf(){for(;Q.ke.length;)tb(Q.ke.length-1);Q.te=[]},Ne:0,te:[],ke:[],vf:(a,b)=>{for(var c=0;c<Q.ke.length;++c)Q.ke[c].target!=a||b&&b!=Q.ke[c].ie||tb(c--)},Lf(a){var b=!1;for(let c=0;c<Q.ke.length;++c){let d=Q.ke[c];d.target===a.target&&d.le===a.le&&d.je===a.je&&d.ne===a.ne&&(tb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled??document.webkitFullscreenEnabled}},zb=[0,document,window],S=a=>{a=
a>2?a?p(q,a):"":a;return zb[a]||document.querySelector(a)},Bb=a=>{var b=Za(a)+1,c=Ab(b);K(a,c,b);return c},Eb=a=>{var b=Cb(),c=Ab(8),d=c+4;a=Bb(a.id);if(a=S(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];Db(b);return c},Fb=(a,b,c)=>{a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},Gb=(a,b,c)=>{if(a.Af){var d=Cb();a=Bb(a.id);Fb(a,b,c);Db(d)}else a.width=b,a.height=c},Hb=0,Ib=[],T=a=>{var b=Ib[a];b||(Ib[a]=b=Jb.get(a));return b},Kb=a=>{function b(){if(!(document.fullscreenElement??document.webkitFullscreenElement)){document.removeEventListener("fullscreenchange",
b);document.removeEventListener("webkitfullscreenchange",b);Gb(a,d,e);a.style.width=g;a.style.height=f;a.style.backgroundColor=l;m||(document.body.style.backgroundColor="white");document.body.style.backgroundColor=m;a.style.paddingLeft=t;a.style.paddingRight=B;a.style.paddingTop=L;a.style.paddingBottom=I;a.style.marginLeft=Uc;a.style.marginRight=Vc;a.style.marginTop=Wc;a.style.marginBottom=Xc;document.body.style.margin=Yc;document.documentElement.style.overflow=Zc;document.body.scroll=$c;a.style.imageRendering=
ad;a.we&&a.we.se.viewport(0,0,d,e);var Ua=Hb;Ua.Ae&&T(Ua.Ae)(37,0,Ua.Ze)}}var c=Eb(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,Uc=a.style.marginLeft,Vc=a.style.marginRight,Wc=a.style.marginTop,Xc=a.style.marginBottom,Yc=document.body.style.margin,Zc=document.documentElement.style.overflow,$c=document.body.scroll,ad=a.style.imageRendering;document.addEventListener("fullscreenchange",
b);document.addEventListener("webkitfullscreenchange",b)},Lb=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Mb=a=>zb.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},Nb=(a,b)=>{if(b.Re!=0||b.Ie!=0){Kb(a);var c=b.wf?innerWidth:screen.width,d=b.wf?innerHeight:screen.height,e=Mb(a),g=e.width;e=e.height;var f=Eb(a),l=f[0];f=f[1];b.Re==3?(Lb(a,(d-e)/2,(c-g)/2),c=g,d=e):b.Re==2&&(c*f<l*d?(g=f*c/l,Lb(a,(d-g)/2,0),d=g):(g=l*d/f,Lb(a,0,(c-g)/
2),c=g));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";b.rf==1&&(a.style.imageRendering="optimizeSpeed",a.style.imageRendering="-moz-crisp-edges",a.style.imageRendering="-o-crisp-edges",a.style.imageRendering="-webkit-optimize-contrast",a.style.imageRendering="optimize-contrast",a.style.imageRendering="crisp-edges",a.style.imageRendering="pixelated");m=b.Ie==2?devicePixelRatio:
1;b.Ie!=0&&(c=c*m|0,d=d*m|0,Gb(a,c,d),a.we&&a.we.se.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Q.fullscreenEnabled()?-3:-1;Hb=b;b.Ae&&T(b.Ae)(37,0,b.Ze);return 0},Ob=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},U,Pb=(a,b)=>{P[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)P[a+c*8+16>>3]=b.axes[c];for(c=0;c<
b.buttons.length;++c)U[a+c+1040]=b.buttons[c].pressed,P[a+c*8+528>>3]=b.buttons[c].value;U[a+1104]=b.connected;r[a+1108>>2]=b.index;r[a+8>>2]=b.axes.length;r[a+12>>2]=b.buttons.length;K(b.id,a+1112,64);K(b.mapping,a+1176,64)},Qb=(a,b)=>{z.attachShader(C[a],G[b])},Rb=(a,b)=>{z.bindBuffer(a,A[b])},Sb=a=>z.blendEquation(a),Tb=(a,b)=>z.blendFunc(a,b),Ub=(a,b,c,d)=>{z.bufferData(a,c?q.subarray(c,c+b):b,d)},Vb=a=>z.clear(a),Wb=(a,b,c,d)=>z.clearColor(a,b,c,d),Xb=a=>{z.compileShader(G[a])},Yb=()=>{var a=
Va(C),b=z.createProgram();b.name=a;b.Ge=b.Ee=b.Fe=0;b.Ve=1;C[a]=b;return a},Zb=a=>{var b=Va(G);G[b]=z.createShader(a);return b},$b=a=>{if(a){var b=G[a];b?(z.deleteShader(b),G[a]=null):J||=1281}},ac=a=>{z.depthMask(!!a)},bc=a=>z.disable(a),cc=[],dc=(a,b,c,d)=>{z.drawElements(a,b,c,d)},ec=a=>z.enable(a),fc=a=>{z.enableVertexAttribArray(a)},hc=(a,b)=>{Wa(a,b,"createBuffer",A)},ic=(a,b,c,d,e,g,f,l)=>{b=C[b];if(a=z[a](b,c))d=l&&K(a.name,l,d),e&&(r[e>>2]=d),g&&(r[g>>2]=a.size),f&&(r[f>>2]=a.type)},jc=(a,
b)=>z.getAttribLocation(C[a],b?p(q,b):""),V,kc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:c!=0&&c!=1&&(J||=1280);return;case 36345:d=0;break;case 34466:var e=z.getParameter(34467);d=e?e.length:0}if(d===void 0)switch(e=z.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":J||=1280;return;case "object":if(e===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:J||=
1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+a*4>>2]=e[a];break;case 2:V[b+a*4>>2]=e[a];break;case 4:U[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){J||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:J||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:r[b>>2]=d;break;case 2:V[b>>2]=d;break;case 4:U[b]=d?1:0}}else J||=1281},lc=(a,b,c)=>{if(c){a=z.re.getQueryObjectEXT(H[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;u[c>>2]=d;u[c+4>>2]=(d-u[c>>2])/4294967296}else J||=1281},mc=(a,b,c)=>{if(c){a=z.re.getQueryObjectEXT(H[a],b);var d;typeof a=="boolean"?d=a?1:0:d=a;r[c>>2]=d}else J||=1281},nc=()=>{var a=Oa(z);return a=a.concat(a.map(b=>"GL_"+b))},oc=a=>a.slice(-1)=="]"&&
a.lastIndexOf("["),pc=a=>{var b=a.ye,c=a.ff,d;if(!b){a.ye=b={};a.ef={};var e=z.getProgramParameter(a,35718);for(d=0;d<e;++d){var g=z.getActiveUniform(a,d);var f=g.name;g=g.size;var l=oc(f);l=l>0?f.slice(0,l):f;var m=a.Ve;a.Ve+=g;c[l]=[g,m];for(f=0;f<g;++f)b[m]=f,a.ef[m++]=l}}},qc=(a,b)=>{b=b?p(q,b):"";if(a=C[a]){pc(a);var c=a.ye,d=0,e=b,g=oc(b);g>0&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.ff[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||z.getUniformLocation(a,b)))return d}else J||=1281;return-1},
W=(a,b)=>{if(a){var c=a.ye[b];typeof c=="number"&&(a.ye[b]=c=z.getUniformLocation(a,a.ef[b]+(c>0?`[${c}]`:"")));return c}J||=1282},rc=(a,b,c,d)=>{if(c)if(a=C[a],pc(a),a=z.getUniform(a,W(a,b)),typeof a=="number"||typeof a=="boolean")switch(d){case 0:r[c>>2]=a;break;case 2:V[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+b*4>>2]=a[b];break;case 2:V[c+b*4>>2]=a[b]}else J||=1281},sc=(a,b,c,d)=>{if(c)if(a=z.getVertexAttrib(a,b),b==34975)r[c>>2]=a&&a.name;else if(typeof a=="number"||typeof a==
"boolean")switch(d){case 0:r[c>>2]=a;break;case 2:V[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+b*4>>2]=a[b];break;case 2:V[c+b*4>>2]=a[b];break;case 5:r[c+b*4>>2]=Math.fround(a[b])}else J||=1281},tc=a=>{a=C[a];z.linkProgram(a);a.ye=0;a.ff={}},uc,vc=(a,b,c,d,e)=>{a-=5120;a=a==1?q:a==4?r:a==6?V:a==5||a==28922?u:uc;b=d*(({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT*(Ta||c)+Sa-1&-Sa);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},wc=(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var f=(f=u[c+g*4>>2])?p(q,f,d?u[d+g*4>>2]:void 0):"";e+=f}z.shaderSource(G[a],e)},xc=(a,b)=>{z.uniform1f(W(z.ge,a),b)},X=[],yc=[],zc=(a,b,c,d)=>{z.uniform3f(W(z.ge,a),b,c,d)},Ac=(a,b,c,d)=>{if(b<=18){var e=X[16*b],g=V;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=g[l];e[f+1]=g[l+1];e[f+2]=g[l+2];e[f+3]=g[l+3];e[f+4]=g[l+4];e[f+5]=g[l+5];e[f+6]=g[l+6];e[f+7]=g[l+7];e[f+8]=g[l+8];e[f+9]=g[l+9];e[f+10]=g[l+10];e[f+
11]=g[l+11];e[f+12]=g[l+12];e[f+13]=g[l+13];e[f+14]=g[l+14];e[f+15]=g[l+15]}}else e=V.subarray(d>>2,d+b*64>>2);z.uniformMatrix4fv(W(z.ge,a),!!c,e)},Bc=a=>{a=C[a];z.useProgram(a);z.ge=a},Cc=(a,b,c,d,e,g)=>{z.vertexAttribPointer(a,b,c,!!d,e,g)},Dc=(a,b,c,d)=>z.viewport(a,b,c,d),Ec=(a,b)=>{if(!Q.fullscreenEnabled())return-1;a=S(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?wb()?Nb(a,b):b.mf?(ub(Nb,1,[a,b]),1):-2:-3:-4},Fc,Gc=()=>{try{if(navigator.getGamepads)return(Q.De=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},Hc=(a,b)=>{var c={target:S(2),ie:"beforeunload",le:28,ne:a,je:b,oe:d=>{var e=T(b)(28,0,a);e&&=e?p(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},me:!0};return R(c)},Ic=(a,b,c,d,e,g)=>{Q.Ke||(Q.Ke=M(256));a={target:S(a),ie:g,le:e,ne:b,je:d,oe:f=>{var l=f.target.id??"",m=Q.Ke;K(yb(f.target),m+0,128);K(l,m+128,128);T(d)(e,m,b)&&f.preventDefault()},me:c};return R(a)},Jc=(a,b,c,d,e)=>{Q.Le||(Q.Le=M(276));return R({target:a,ie:e,le:19,ne:b,je:d,
oe:g=>{var f=Q.Le,l=document.fullscreenElement??document.webkitFullscreenElement,m=!!l;U[f]=m;U[f+1]=Q.fullscreenEnabled();var t=m?l:Q.uf,B=t?.id??"";K(yb(t),f+2,128);K(B,f+130,128);r[f+260>>2]=t?.clientWidth??0;r[f+264>>2]=t?.clientHeight??0;r[f+268>>2]=screen.width;r[f+272>>2]=screen.height;m&&(Q.uf=l);T(d)(19,f,b)&&g.preventDefault()},me:c})},Kc=(a,b,c,d,e)=>{Q.Me||(Q.Me=M(1240));b={target:S(2),ze:!0,ie:e,le:d,ne:a,je:c,oe:g=>{var f=Q.Me;Pb(f,g.gamepad);T(c)(d,f,a)&&g.preventDefault()},me:b};return R(b)},
Lc=(a,b,c,d,e,g)=>{Q.Oe||(Q.Oe=M(160));a={target:S(a),ie:g,le:e,ne:b,je:d,oe:f=>{var l=Q.Oe;P[l>>3]=f.timeStamp;var m=l>>2;r[m+2]=f.location;U[l+12]=f.ctrlKey;U[l+13]=f.shiftKey;U[l+14]=f.altKey;U[l+15]=f.metaKey;U[l+16]=f.repeat;r[m+5]=f.charCode;r[m+6]=f.keyCode;r[m+7]=f.which;K(f.key??"",l+32,32);K(f.code??"",l+64,32);K(f.char??"",l+96,32);K(f.locale??"",l+128,32);T(d)(e,l,b)&&f.preventDefault()},me:c};return R(a)},Mc=(a,b,c)=>{P[a>>3]=b.timeStamp;var d=a>>2;r[d+2]=b.screenX;r[d+3]=b.screenY;r[d+
4]=b.clientX;r[d+5]=b.clientY;U[a+24]=b.ctrlKey;U[a+25]=b.shiftKey;U[a+26]=b.altKey;U[a+27]=b.metaKey;Fc[d*2+14]=b.button;Fc[d*2+15]=b.buttons;r[d+8]=b.movementX;r[d+9]=b.movementY;a=Mb(c);r[d+10]=b.clientX-(a.left|0);r[d+11]=b.clientY-(a.top|0)},Nc=(a,b,c,d,e,g)=>{Q.He||(Q.He=M(64));a=S(a);return R({target:a,ze:g!="mousemove"&&g!="mouseenter"&&g!="mouseleave",ie:g,le:e,ne:b,je:d,oe:f=>{Mc(Q.He,f,a);T(d)(e,Q.He,b)&&f.preventDefault()},me:c})},Oc=(a,b,c,d)=>{Q.Qe||(Q.Qe=M(257));return R({target:a,
ie:"pointerlockchange",le:20,ne:b,je:d,oe:e=>{var g=Q.Qe,f=document.pointerLockElement;U[g]=!!f;var l=f?.id??"";K(yb(f),g+1,128);K(l,g+129,128);T(d)(20,g,b)&&e.preventDefault()},me:c})},Pc=(a,b,c,d)=>{Q.Ue||(Q.Ue=M(36));a=S(a);return R({target:a,ie:"resize",le:10,ne:b,je:d,oe:e=>{if(e.target==a){var g=document.body;if(g){var f=Q.Ue;r[f>>2]=0;r[f+4>>2]=g.clientWidth;r[f+8>>2]=g.clientHeight;r[f+12>>2]=innerWidth;r[f+16>>2]=innerHeight;r[f+20>>2]=outerWidth;r[f+24>>2]=outerHeight;r[f+28>>2]=pageXOffset|
0;r[f+32>>2]=pageYOffset|0;T(d)(10,f,b)&&e.preventDefault()}}},me:c})},Qc=(a,b,c,d,e,g)=>{Q.Te||(Q.Te=M(1552));a=S(a);return R({target:a,ze:g=="touchstart"||g=="touchend",ie:g,le:e,ne:b,je:d,oe:f=>{var l={},m=f.touches;for(var t of m)t.af=t.cf=0,l[t.identifier]=t;for(var B of f.changedTouches)B.af=1,l[B.identifier]=B;for(var L of f.targetTouches)l[L.identifier].cf=1;m=Q.Te;P[m>>3]=f.timeStamp;U[m+12]=f.ctrlKey;U[m+13]=f.shiftKey;U[m+14]=f.altKey;U[m+15]=f.metaKey;t=m+16;B=Mb(a);L=0;for(let I of Object.values(l))if(l=
t>>2,r[l]=I.identifier,r[l+1]=I.screenX,r[l+2]=I.screenY,r[l+3]=I.clientX,r[l+4]=I.clientY,r[l+5]=I.pageX,r[l+6]=I.pageY,U[t+28]=I.af,U[t+29]=I.cf,r[l+8]=I.clientX-(B.left|0),r[l+9]=I.clientY-(B.top|0),t+=48,++L>31)break;r[m+8>>2]=L;T(d)(e,m,b)&&f.preventDefault()},me:c})},Rc=(a,b,c)=>{var d=zb[1];Q.We||(Q.We=M(8));return R({target:d,ie:"visibilitychange",le:21,ne:a,je:c,oe:e=>{var g=Q.We,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);U[g]=document.hidden;r[g+4>>2]=
f;T(c)(21,g,a)&&e.preventDefault()},me:b})},Sc=(a,b,c,d)=>{Q.Xe||(Q.Xe=M(96));return R({target:a,ze:!0,ie:"wheel",le:9,ne:b,je:d,oe:e=>{var g=Q.Xe;Mc(g,e,a);P[g+64>>3]=e.deltaX;P[g+72>>3]=e.deltaY;P[g+80>>3]=e.deltaZ;r[g+88>>2]=e.deltaMode;T(d)(9,g,b)&&e.preventDefault()},me:c})},Tc={},cd=()=>{if(!bd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba},b;for(b in Tc)Tc[b]===void 0?delete a[b]:a[b]=
Tc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);bd=c}return bd},bd,dd=[null,[],[]],ed=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{a.state==="suspended"&&a.resume()},{once:!0})},fd=(a,b=[])=>{T(a)(...b)};
function gd(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":U[a]=b;break;case "i8":U[a]=b;break;case "i16":Fc[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":ua[a>>3]=BigInt(b);break;case "float":V[a>>2]=b;break;case "double":P[a>>3]=b;break;case "*":u[a>>2]=b;break;default:ma(`invalid type for setValue: ${c}`)}}h.requestAnimationFrame=pb;h.pauseMainLoop=function(){O&&(O=null,$a++)};h.resumeMainLoop=function(){$a++;var a=hb,b=ib,c=ab;ab=null;nb(c,0,!1,bb,!0);mb(a,b);O()};
for(let a=0;a<32;++a)cc.push(Array(a));for(var hd=new Float32Array(288),Y=0;Y<=288;++Y)X[Y]=hd.subarray(0,Y);var jd=new Int32Array(288);for(Y=0;Y<=288;++Y)yc[Y]=jd.subarray(0,Y);h.noExitRuntime&&(sa=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);var Z=h.preInit;if(Z)for(typeof Z=="function"&&(h.preInit=Z=[Z]);Z.length>0;)Z.shift()();h.createContext=Ca;
var kd={94230:()=>{window.he||(window.he=new Audio);window.xe=void 0;window.ve=!1;var a=window.he;a.src="end.mp3";a.load();a.addEventListener("canplaythrough",function(){window.xe=a.duration},{once:!0});a.play().catch(function(b){window.ve=!0;console.error("Audio play failed:",b)});a.onerror=function(){window.ve=!0;console.error("Audio load error:",a.error)}},94722:(a,b)=>{window.he||(window.he=new Audio);window.xe=void 0;window.ve=!1;var c=window.he;c.src="track"+b+"/v"+a+".mp3";c.load();c.addEventListener("canplaythrough",
function(){window.xe=c.duration},{once:!0});c.play().catch(function(d){window.ve=!0;console.error("Audio play failed:",d)});c.onerror=function(){window.ve=!0;console.error("Audio load error:",c.error)}},95278:()=>{window.xe=void 0},95309:()=>typeof AudioContext!=="undefined"||typeof webkitAudioContext!=="undefined"?!0:!1,95456:()=>typeof navigator.mediaDevices!=="undefined"&&typeof navigator.mediaDevices.getUserMedia!=="undefined"||typeof navigator.webkitGetUserMedia!=="undefined"?!0:!1,95690:a=>
{typeof h.SDL2==="undefined"&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.fe||(typeof AudioContext!=="undefined"?b.fe=new AudioContext:typeof webkitAudioContext!=="undefined"&&(b.fe=new webkitAudioContext),b.fe&&typeof navigator.userActivation==="undefined"&&ed(b.fe));return b.fe===void 0?-1:0},96242:()=>h.SDL2.fe.sampleRate,96310:(a,b,c,d)=>{function e(){}function g(l){f.capture.qe!==void 0&&(clearInterval(f.capture.qe),f.capture.qe=void 0,f.capture.ue=void 0);f.capture.Pe=f.fe.createMediaStreamSource(l);
f.capture.pe=f.fe.createScriptProcessor(b,a,1);f.capture.pe.onaudioprocess=function(m){f!==void 0&&f.capture!==void 0&&(m.outputBuffer.getChannelData(0).fill(0),f.capture.Je=m.inputBuffer,fd(c,[d]))};f.capture.Pe.connect(f.capture.pe);f.capture.pe.connect(f.fe.destination);f.capture.stream=l}var f=h.SDL2;f.capture.ue=f.fe.createBuffer(a,b,f.fe.sampleRate);f.capture.ue.getChannelData(0).fill(0);f.capture.qe=setInterval(function(){f.capture.Je=f.capture.ue;fd(c,[d])},b/f.fe.sampleRate*1E3);navigator.mediaDevices!==
void 0&&navigator.mediaDevices.getUserMedia!==void 0?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):navigator.webkitGetUserMedia!==void 0&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},98003:(a,b,c,d)=>{var e=h.SDL2;e.audio.pe=e.fe.createScriptProcessor(b,0,a);e.audio.pe.onaudioprocess=function(g){e!==void 0&&e.audio!==void 0&&(e.audio.qe!==void 0&&(clearInterval(e.audio.qe),e.audio.qe=void 0,e.audio.ue=void 0),e.audio.Ce=g.outputBuffer,fd(c,[d]))};e.audio.pe.connect(e.fe.destination);
e.fe.state==="suspended"&&(e.audio.ue=e.fe.createBuffer(a,b,e.fe.sampleRate),e.audio.ue.getChannelData(0).fill(0),e.audio.qe=setInterval(function(){typeof navigator.userActivation!=="undefined"&&navigator.userActivation.hasBeenActive&&e.fe.resume();e.audio.Ce=e.audio.ue;fd(c,[d]);e.audio.Ce=void 0},b/e.fe.sampleRate*1E3))},99178:(a,b)=>{for(var c=h.SDL2,d=c.capture.Je.numberOfChannels,e=0;e<d;++e){var g=c.capture.Je.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+
g.length+" samples vs expected "+b+" samples!";if(d==1)for(var f=0;f<b;++f)gd(a+f*4,g[f]);else for(f=0;f<b;++f)gd(a+(f*d+e)*4,g[f])}},99783:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.Ce.numberOfChannels,e=0;e<d;++e){var g=c.audio.Ce.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=V[a+(f*d+e)]}},100272:a=>{var b=h.SDL2;if(a){b.capture.qe!==void 0&&clearInterval(b.capture.qe);
if(b.capture.stream!==void 0){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}b.capture.pe!==void 0&&(b.capture.pe.onaudioprocess=function(){},b.capture.pe.disconnect());b.capture.Pe!==void 0&&b.capture.Pe.disconnect();b.capture=void 0}else b.audio.pe!=void 0&&b.audio.pe.disconnect(),b.audio.qe!==void 0&&clearInterval(b.audio.qe),b.audio=void 0;b.fe!==void 0&&b.audio===void 0&&b.capture===void 0&&(b.fe.close(),b.fe=void 0)},101278:(a,b,c)=>{h.SDL2||
(h.SDL2={});var d=h.SDL2;d.gf!==h.canvas&&(d.Be=Ca(h.canvas,!1,!0),d.gf=h.canvas);if(d.w!==a||d.h!==b||d.sf!==d.Be)d.image=d.Be.createImageData(a,b),d.w=a,d.h=b,d.sf=d.Be;a=d.image.data;b=c/4;var e=0;if(typeof CanvasPixelArray!=="undefined"&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=r[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.kf!==a&&(d.jf=new Int32Array(a.buffer),d.lf=new Uint8Array(a.buffer),d.kf=a),a=d.jf,c=a.length,a.set(r.subarray(b,b+c)),a=d.lf,
b=3,e=b+4*c,c%8==0)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Be.putImageData(d.image,0,0)},102744:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e/=4;var l=0,m;if(typeof CanvasPixelArray!=="undefined"&&b instanceof CanvasPixelArray)for(m=b.length;l<m;){var t=r[e];b[l]=t&255;b[l+
1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(r.subarray(e,e+m));f.putImageData(a,0,0);c=c===0&&d===0?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=M(c.length+1);K(c,d,c.length+1);return d},103732:a=>{h.canvas&&(h.canvas.style.cursor=a?p(q,a):"")},103815:()=>{h.canvas&&(h.canvas.style.cursor="none")},103884:()=>window.innerWidth,103914:()=>window.innerHeight},ld,M,Db,Ab,Cb,md,Jb,nd={$:function(){return 0},Ya:function(){return 0},
Za:function(){},Sa:()=>{},Ha:a=>{if(a==12448)return w=12288,1;w=12300;return 0},Ka:(a,b,c,d,e)=>{if(a!=62E3)w=12296,c=0;else{if(b)for(;;){a=r[b>>2];if(a==12321)x.alpha=r[b+4>>2]>0;else if(a==12325)x.depth=r[b+4>>2]>0;else if(a==12326)x.stencil=r[b+4>>2]>0;else if(a==12337)a=r[b+4>>2],x.antialias=a>0;else if(a==12338)a=r[b+4>>2],x.antialias=a==1;else if(a==12544)x.Gf=r[b+4>>2]!=12547;else if(a==12344)break;b+=8}c&&d||e?(e&&(r[e>>2]=1),c&&d>0&&(u[c>>2]=62002),w=12288,c=1):(w=12300,c=0)}return c},ya:(a,
b,c,d)=>{if(a!=62E3)return w=12296,0;for(a=1;;){b=r[d>>2];if(b==12440)a=r[d+4>>2];else if(b==12344)break;else return w=12292,0;d+=8}if(a!=2)return w=12293,0;x.bf=a-1;x.Hf=0;y=Ea(h.canvas,x);if(y!=0)return w=12288,Fa(y),za.forEach(e=>e()),Fa(null),62004;w=12297;return 0},Aa:(a,b)=>{if(a!=62E3)return w=12296,0;if(b!=62002)return w=12293,0;w=12288;return 62006},za:(a,b)=>{if(a!=62E3)return w=12296,0;if(b!=62004)return w=12294,0;a=y;Ya===v[a]&&(Ya=null);typeof Q=="object"&&Q.vf(v[a].se.canvas);v[a]?.se.canvas&&
(v[a].se.canvas.we=void 0);v[a]=null;w=12288;Ha==b&&(Ha=0);return 1},Ba:(a,b)=>{if(a!=62E3)return w=12296,0;if(b!=62006)return w=12301,1;Ia==b&&(Ia=0);Ja==b&&(Ja=0);w=12288;return 1},La:(a,b,c,d)=>{if(a!=62E3)return w=12296,0;if(b!=62002)return w=12293,0;if(!d)return w=12300,0;w=12288;switch(c){case 12320:return r[d>>2]=x.alpha?32:24,1;case 12321:return r[d>>2]=x.alpha?8:0,1;case 12322:return r[d>>2]=8,1;case 12323:return r[d>>2]=8,1;case 12324:return r[d>>2]=8,1;case 12325:return r[d>>2]=x.depth?
24:0,1;case 12326:return r[d>>2]=x.stencil?8:0,1;case 12327:return r[d>>2]=12344,1;case 12328:return r[d>>2]=62002,1;case 12329:return r[d>>2]=0,1;case 12330:return r[d>>2]=4096,1;case 12331:return r[d>>2]=16777216,1;case 12332:return r[d>>2]=4096,1;case 12333:return r[d>>2]=0,1;case 12334:return r[d>>2]=0,1;case 12335:return r[d>>2]=12344,1;case 12337:return r[d>>2]=x.antialias?4:0,1;case 12338:return r[d>>2]=x.antialias?1:0,1;case 12339:return r[d>>2]=4,1;case 12340:return r[d>>2]=12344,1;case 12341:case 12342:case 12343:return r[d>>
2]=-1,1;case 12345:case 12346:return r[d>>2]=0,1;case 12347:return r[d>>2]=0,1;case 12348:return r[d>>2]=1;case 12349:case 12350:return r[d>>2]=0,1;case 12351:return r[d>>2]=12430,1;case 12352:return r[d>>2]=4,1;case 12354:return r[d>>2]=0,1;default:return w=12292,0}},P:a=>{w=12288;return a!=0&&a!=1?0:62E3},xa:()=>w,Ia:(a,b,c)=>{if(a!=62E3)return w=12296,0;b&&(r[b>>2]=1);c&&(r[c>>2]=4);Ga=!0;w=12288;return 1},Ca:(a,b,c,d)=>{if(a!=62E3)return w=12296,0;if(d!=0&&d!=62004)return w=12294,0;if(c!=0&&c!=
62006||b!=0&&b!=62006)return w=12301,0;Fa(d?y:null);Ha=d;Ja=b;Ia=c;w=12288;return 1},wa:(a,b)=>{if(a!=62E3)return w=12296,0;w=12288;if(Ka[b])return Ka[b];switch(b){case 12371:a=N("Emscripten");break;case 12372:a=N("1.4 Emscripten EGL");break;case 12373:a=N("");break;case 12429:a=N("OpenGL_ES");break;default:return w=12300,0}return Ka[b]=a},Da:()=>{if(Ga)if(z)if(z.isContextLost())w=12302;else return w=12288,1;else w=12290;else w=12289;return 0},Ea:(a,b)=>{if(a!=62E3)return w=12296,0;b==0?mb(0,0):mb(1,
b);w=12288;return 1},Ja:a=>{if(a!=62E3)return w=12296,0;Ja=Ia=Ha=0;Ga=!1;w=12288;return 1},Ga:()=>{w=12288;return 1},Fa:()=>{w=12288;return 1},n:(a,b,c)=>{b=sb(b,c);return kd[a](...b)},i:(a,b,c)=>{b=sb(b,c);return kd[a](...b)},ua:(a,b,c)=>{b=sb(b,c);return kd[a](...b)},aa:()=>Date.now(),pa:()=>{if(!Q.fullscreenEnabled())return-1;vb(Nb);var a=zb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;
return 0},ta:()=>{vb(Ob);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},m:()=>devicePixelRatio,k:(a,b,c)=>{a=S(a);if(!a)return-4;a=Mb(a);P[b>>3]=a.width;P[c>>3]=a.height;return 0},T:(a,b)=>{if(a<0||a>=Q.De.length)return-5;if(!Q.De[a])return-7;Pb(b,Q.De[a]);return 0},Y:()=>performance.now(),Ma:()=>Q.De.length,va:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},Od:a=>z.activeTexture(a),Nd:Qb,la:(a,b)=>{z.re.beginQueryEXT(a,H[b])},Md:(a,b,c)=>{z.bindAttribLocation(C[a],
b,c?p(q,c):"")},Ld:Rb,Kd:(a,b)=>{z.bindFramebuffer(a,D[b])},Jd:(a,b)=>{z.bindRenderbuffer(a,E[b])},Id:(a,b)=>{z.bindTexture(a,F[b])},Wd:a=>{z.bindVertexArray(Qa[a])},Hd:(a,b,c,d)=>z.blendColor(a,b,c,d),Gd:Sb,Fd:(a,b)=>z.blendEquationSeparate(a,b),Ed:Tb,Cd:(a,b,c,d)=>z.blendFuncSeparate(a,b,c,d),Bd:Ub,Ad:(a,b,c,d)=>{z.bufferSubData(a,b,q.subarray(d,d+c))},zd:a=>z.checkFramebufferStatus(a),yd:Vb,xd:Wb,wd:a=>z.clearDepth(a),vd:a=>z.clearStencil(a),$a:(a,b)=>{z.pf.clipControlEXT(a,b)},ud:(a,b,c,d)=>{z.colorMask(!!a,
!!b,!!c,!!d)},td:Xb,sd:(a,b,c,d,e,g,f,l)=>{z.compressedTexImage2D(a,b,c,d,e,g,q.subarray(l,l+f))},rd:(a,b,c,d,e,g,f,l,m)=>{z.compressedTexSubImage2D(a,b,c,d,e,g,f,q.subarray(m,m+l))},qd:(a,b,c,d,e,g,f,l)=>z.copyTexImage2D(a,b,c,d,e,g,f,l),pd:(a,b,c,d,e,g,f,l)=>z.copyTexSubImage2D(a,b,c,d,e,g,f,l),od:Yb,nd:Zb,md:a=>z.cullFace(a),ld:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=A[d];e&&(z.deleteBuffer(e),e.name=0,A[d]=null)}},kd:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+c*4>>2],e=D[d];e&&(z.deleteFramebuffer(e),
e.name=0,D[d]=null)}},jd:a=>{if(a){var b=C[a];b?(z.deleteProgram(b),b.name=0,C[a]=null):J||=1281}},na:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=H[d];e&&(z.re.deleteQueryEXT(e),H[d]=null)}},hd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=E[d];e&&(z.deleteRenderbuffer(e),e.name=0,E[d]=null)}},gd:$b,fd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2],e=F[d];e&&(z.deleteTexture(e),e.name=0,F[d]=null)}},Vd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+c*4>>2];z.deleteVertexArray(Qa[d]);Qa[d]=null}},
ed:a=>z.depthFunc(a),dd:ac,cd:(a,b)=>z.depthRange(a,b),bd:(a,b)=>{z.detachShader(C[a],G[b])},ad:bc,$c:a=>{z.disableVertexAttribArray(a)},_c:(a,b,c)=>{z.drawArrays(a,b,c)},Rd:(a,b,c,d)=>{z.drawArraysInstanced(a,b,c,d)},Sd:(a,b)=>{for(var c=cc[a],d=0;d<a;d++)c[d]=r[b+d*4>>2];z.drawBuffers(c)},Yc:dc,Qd:(a,b,c,d,e)=>{z.drawElementsInstanced(a,b,c,d,e)},Xc:ec,Wc:fc,ka:a=>{z.re.endQueryEXT(a)},Vc:()=>z.finish(),Uc:()=>z.flush(),Tc:(a,b,c,d)=>{z.framebufferRenderbuffer(a,b,c,E[d])},Sc:(a,b,c,d,e)=>{z.framebufferTexture2D(a,
b,c,F[d],e)},Rc:a=>z.frontFace(a),Qc:hc,Oc:(a,b)=>{Wa(a,b,"createFramebuffer",D)},oa:(a,b)=>{for(var c=0;c<a;c++){var d=z.re.createQueryEXT();if(!d){for(J||=1282;c<a;)r[b+c++*4>>2]=0;break}var e=Va(H);d.name=e;H[e]=d;r[b+c*4>>2]=e}},Nc:(a,b)=>{Wa(a,b,"createRenderbuffer",E)},Mc:(a,b)=>{Wa(a,b,"createTexture",F)},Ud:(a,b)=>{Wa(a,b,"createVertexArray",Qa)},Pc:a=>z.generateMipmap(a),Lc:(a,b,c,d,e,g,f)=>ic("getActiveAttrib",a,b,c,d,e,g,f),Kc:(a,b,c,d,e,g,f)=>ic("getActiveUniform",a,b,c,d,e,g,f),Jc:(a,
b,c,d)=>{a=z.getAttachedShaders(C[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+b*4>>2]=G.indexOf(a[b])},Ic:jc,Hc:(a,b)=>kc(a,b,4),Gc:(a,b,c)=>{c?r[c>>2]=z.getBufferParameter(a,b):J||=1281},Fc:()=>{var a=z.getError()||J;J=0;return a},Ec:(a,b)=>kc(a,b,2),Dc:(a,b,c,d)=>{a=z.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},Cc:(a,b)=>kc(a,b,0),Ac:(a,b,c,d)=>{a=z.getProgramInfoLog(C[a]);a===null&&(a="(unknown error)");
b=b>0&&d?K(a,d,b):0;c&&(r[c>>2]=b)},Bc:(a,b,c)=>{if(c)if(a>=Pa)J||=1281;else if(a=C[a],b==35716)a=z.getProgramInfoLog(a),a===null&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(b==35719){if(!a.Ge){var d=z.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ge=Math.max(a.Ge,z.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.Ge}else if(b==35722){if(!a.Ee)for(d=z.getProgramParameter(a,35721),b=0;b<d;++b)a.Ee=Math.max(a.Ee,z.getActiveAttrib(a,b).name.length+1);r[c>>2]=a.Ee}else if(b==35381){if(!a.Fe)for(d=
z.getProgramParameter(a,35382),b=0;b<d;++b)a.Fe=Math.max(a.Fe,z.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.Fe}else r[c>>2]=z.getProgramParameter(a,b);else J||=1281},fa:lc,ha:mc,Xd:lc,ga:mc,ia:(a,b,c)=>{c?r[c>>2]=z.re.getQueryEXT(a,b):J||=1281},zc:(a,b,c)=>{c?r[c>>2]=z.getRenderbufferParameter(a,b):J||=1281},xc:(a,b,c,d)=>{a=z.getShaderInfoLog(G[a]);a===null&&(a="(unknown error)");b=b>0&&d?K(a,d,b):0;c&&(r[c>>2]=b)},wc:(a,b,c,d)=>{a=z.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>
2]=a.rangeMax;r[d>>2]=a.precision},vc:(a,b,c,d)=>{if(a=z.getShaderSource(G[a]))b=b>0&&d?K(a,d,b):0,c&&(r[c>>2]=b)},yc:(a,b,c)=>{c?b==35716?(a=z.getShaderInfoLog(G[a]),a===null&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):b==35720?(a=z.getShaderSource(G[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=z.getShaderParameter(G[a],b):J||=1281},uc:a=>{var b=Ra[a];if(!b){switch(a){case 7939:b=N(nc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=z.getParameter(a))||(J||=1280);b=b?N(b):0;break;case 7938:b=
N(`OpenGL ES 2.0 (${z.getParameter(7938)})`);break;case 35724:b=z.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);c!==null&&(c[1].length==3&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=N(b);break;default:J||=1280}Ra[a]=b}return b},tc:(a,b,c)=>{c?V[c>>2]=z.getTexParameter(a,b):J||=1281},sc:(a,b,c)=>{c?r[c>>2]=z.getTexParameter(a,b):J||=1281},pc:qc,rc:(a,b,c)=>{rc(a,b,c,2)},qc:(a,b,c)=>{rc(a,b,c,0)},mc:(a,b,c)=>{c?r[c>>2]=z.getVertexAttribOffset(a,b):J||=1281},
oc:(a,b,c)=>{sc(a,b,c,2)},nc:(a,b,c)=>{sc(a,b,c,5)},lc:(a,b)=>z.hint(a,b),kc:a=>(a=A[a])?z.isBuffer(a):0,jc:a=>z.isEnabled(a),ic:a=>(a=D[a])?z.isFramebuffer(a):0,hc:a=>(a=C[a])?z.isProgram(a):0,ma:a=>(a=H[a])?z.re.isQueryEXT(a):0,gc:a=>(a=E[a])?z.isRenderbuffer(a):0,fc:a=>(a=G[a])?z.isShader(a):0,ec:a=>(a=F[a])?z.isTexture(a):0,Td:a=>(a=Qa[a])?z.isVertexArray(a):0,dc:a=>z.lineWidth(a),cc:tc,bc:(a,b)=>{a==3317?Sa=b:a==3314&&(Ta=b);z.pixelStorei(a,b)},_a:(a,b)=>{z.xf.polygonModeWEBGL(a,b)},ac:(a,b)=>
z.polygonOffset(a,b),ab:(a,b,c)=>{z.qf.polygonOffsetClampEXT(a,b,c)},ja:(a,b)=>{z.re.queryCounterEXT(H[a],b)},$b:(a,b,c,d,e,g,f)=>{(f=vc(g,e,c,d,f))?z.readPixels(a,b,c,d,e,g,f):J||=1280},_b:()=>{},Zb:(a,b,c,d)=>z.renderbufferStorage(a,b,c,d),Yb:(a,b)=>{z.sampleCoverage(a,!!b)},Xb:(a,b,c,d)=>z.scissor(a,b,c,d),Wb:()=>{J||=1280},Vb:wc,Ub:(a,b,c)=>z.stencilFunc(a,b,c),Tb:(a,b,c,d)=>z.stencilFuncSeparate(a,b,c,d),Sb:a=>z.stencilMask(a),Rb:(a,b)=>z.stencilMaskSeparate(a,b),Qb:(a,b,c)=>z.stencilOp(a,b,
c),Pb:(a,b,c,d)=>z.stencilOpSeparate(a,b,c,d),Ob:(a,b,c,d,e,g,f,l,m)=>{m=m?vc(l,f,d,e,m):null;z.texImage2D(a,b,c,d,e,g,f,l,m)},Nb:(a,b,c)=>z.texParameterf(a,b,c),Mb:(a,b,c)=>{z.texParameterf(a,b,V[c>>2])},Lb:(a,b,c)=>z.texParameteri(a,b,c),Kb:(a,b,c)=>{z.texParameteri(a,b,r[c>>2])},Jb:(a,b,c,d,e,g,f,l,m)=>{m=m?vc(l,f,e,g,m):null;z.texSubImage2D(a,b,c,d,e,g,f,l,m)},Ib:xc,Hb:(a,b,c)=>{if(b<=288)for(var d=X[b],e=0;e<b;++e)d[e]=V[c+4*e>>2];else d=V.subarray(c>>2,c+b*4>>2);z.uniform1fv(W(z.ge,a),d)},Gb:(a,
b)=>{z.uniform1i(W(z.ge,a),b)},Fb:(a,b,c)=>{if(b<=288)for(var d=yc[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+b*4>>2);z.uniform1iv(W(z.ge,a),d)},Eb:(a,b,c)=>{z.uniform2f(W(z.ge,a),b,c)},Db:(a,b,c)=>{if(b<=144){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=V[c+4*e>>2],d[e+1]=V[c+(4*e+4)>>2]}else d=V.subarray(c>>2,c+b*8>>2);z.uniform2fv(W(z.ge,a),d)},Cb:(a,b,c)=>{z.uniform2i(W(z.ge,a),b,c)},Bb:(a,b,c)=>{if(b<=144){b*=2;for(var d=yc[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=
r.subarray(c>>2,c+b*8>>2);z.uniform2iv(W(z.ge,a),d)},Ab:zc,zb:(a,b,c)=>{if(b<=96){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=V[c+4*e>>2],d[e+1]=V[c+(4*e+4)>>2],d[e+2]=V[c+(4*e+8)>>2]}else d=V.subarray(c>>2,c+b*12>>2);z.uniform3fv(W(z.ge,a),d)},xb:(a,b,c,d)=>{z.uniform3i(W(z.ge,a),b,c,d)},wb:(a,b,c)=>{if(b<=96){b*=3;for(var d=yc[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+b*12>>2);z.uniform3iv(W(z.ge,a),d)},vb:(a,b,c,d,e)=>{z.uniform4f(W(z.ge,
a),b,c,d,e)},ub:(a,b,c)=>{if(b<=72){var d=X[4*b],e=V;c>>=2;b*=4;for(var g=0;g<b;g+=4){var f=c+g;d[g]=e[f];d[g+1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=V.subarray(c>>2,c+b*16>>2);z.uniform4fv(W(z.ge,a),d)},tb:(a,b,c,d,e)=>{z.uniform4i(W(z.ge,a),b,c,d,e)},sb:(a,b,c)=>{if(b<=72){b*=4;for(var d=yc[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+b*16>>2);z.uniform4iv(W(z.ge,a),d)},rb:(a,b,c,d)=>{if(b<=72){b*=4;for(var e=
X[b],g=0;g<b;g+=4)e[g]=V[d+4*g>>2],e[g+1]=V[d+(4*g+4)>>2],e[g+2]=V[d+(4*g+8)>>2],e[g+3]=V[d+(4*g+12)>>2]}else e=V.subarray(d>>2,d+b*16>>2);z.uniformMatrix2fv(W(z.ge,a),!!c,e)},qb:(a,b,c,d)=>{if(b<=32){b*=9;for(var e=X[b],g=0;g<b;g+=9)e[g]=V[d+4*g>>2],e[g+1]=V[d+(4*g+4)>>2],e[g+2]=V[d+(4*g+8)>>2],e[g+3]=V[d+(4*g+12)>>2],e[g+4]=V[d+(4*g+16)>>2],e[g+5]=V[d+(4*g+20)>>2],e[g+6]=V[d+(4*g+24)>>2],e[g+7]=V[d+(4*g+28)>>2],e[g+8]=V[d+(4*g+32)>>2]}else e=V.subarray(d>>2,d+b*36>>2);z.uniformMatrix3fv(W(z.ge,
a),!!c,e)},pb:Ac,ob:Bc,mb:a=>{z.validateProgram(C[a])},lb:(a,b)=>z.vertexAttrib1f(a,b),kb:(a,b)=>{z.vertexAttrib1f(a,V[b>>2])},jb:(a,b,c)=>z.vertexAttrib2f(a,b,c),ib:(a,b)=>{z.vertexAttrib2f(a,V[b>>2],V[b+4>>2])},hb:(a,b,c,d)=>z.vertexAttrib3f(a,b,c,d),gb:(a,b)=>{z.vertexAttrib3f(a,V[b>>2],V[b+4>>2],V[b+8>>2])},fb:(a,b,c,d,e)=>z.vertexAttrib4f(a,b,c,d,e),eb:(a,b)=>{z.vertexAttrib4f(a,V[b>>2],V[b+4>>2],V[b+8>>2],V[b+12>>2])},Pd:(a,b)=>{z.vertexAttribDivisor(a,b)},db:Cc,bb:Dc,q:()=>0,qa:(a,b,c)=>Ec(a,
{Re:r[c>>2],Ie:r[c+4>>2],rf:r[c+8>>2],mf:b,Ae:r[c+12>>2],Ze:r[c+16>>2]}),N:(a,b)=>{a=S(a);return a?a.requestPointerLock?wb()?Ob(a):b?(ub(Ob,2,[a]),1):-2:-1:-4},Ra:()=>!1,ca:a=>{eval(a?p(q,a):"")},U:Gc,u:(a,b,c)=>typeof onbeforeunload=="undefined"?-1:c!==1?-5:Hc(a,b),F:(a,b,c,d)=>Ic(a,b,c,d,12,"blur"),l:Fb,o:(a,b,c)=>{a=S(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},G:(a,b,c,d)=>Ic(a,b,c,d,13,"focus"),w:(a,b,c,d)=>{if(!Q.fullscreenEnabled())return-1;a=S(a);if(!a)return-4;
Jc(a,b,c,d,"webkitfullscreenchange");return Jc(a,b,c,d,"fullscreenchange")},S:(a,b,c)=>Gc()?-1:Kc(a,b,c,26,"gamepadconnected"),R:(a,b,c)=>Gc()?-1:Kc(a,b,c,27,"gamepaddisconnected"),z:(a,b,c,d)=>Lc(a,b,c,d,2,"keydown"),x:(a,b,c,d)=>Lc(a,b,c,d,1,"keypress"),y:(a,b,c,d)=>Lc(a,b,c,d,3,"keyup"),Na:(a,b,c)=>{a=T(a);nb(a,b,c)},M:(a,b,c,d)=>Nc(a,b,c,d,5,"mousedown"),J:(a,b,c,d)=>Nc(a,b,c,d,33,"mouseenter"),I:(a,b,c,d)=>Nc(a,b,c,d,34,"mouseleave"),r:(a,b,c,d)=>Nc(a,b,c,d,8,"mousemove"),K:(a,b,c,d)=>Nc(a,b,
c,d,6,"mouseup"),A:(a,b,c,d)=>document.body?.requestPointerLock?(a=S(a))?Oc(a,b,c,d):-4:-1,s:(a,b,c,d)=>Pc(a,b,c,d),B:(a,b,c,d)=>Qc(a,b,c,d,25,"touchcancel"),D:(a,b,c,d)=>Qc(a,b,c,d,23,"touchend"),C:(a,b,c,d)=>Qc(a,b,c,d,24,"touchmove"),E:(a,b,c,d)=>Qc(a,b,c,d,22,"touchstart"),v:(a,b,c)=>Rc(a,b,c),H:(a,b,c,d)=>(a=S(a))?typeof a.onwheel!="undefined"?Sc(a,b,c,d):-1:-4,ra:a=>document.title=a?p(q,a):"",p:()=>{ma("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},
Ua:(a,b)=>{var c=0,d=0,e;for(e of cd()){var g=b+c;u[a+d>>2]=g;c+=K(e,g,Infinity)+1;d+=4}return 0},Va:(a,b)=>{var c=cd();u[a>>2]=c.length;a=0;for(var d of c)a+=Za(d)+1;u[b>>2]=a;return 0},Z:()=>52,Xa:()=>52,Ta:function(){return 70},_:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var f=u[b>>2],l=u[b+4>>2];b+=8;for(var m=0;m<l;m++){var t=a,B=q[f+m],L=dd[t];B&&B!==10?L.push(B):((t===1?fa:k)(p(L)),L.length=0)}e+=l}u[d>>2]=e;return 0},cb:function(){return!window.he||window.he.paused||window.he.ended?0:window.he.duration-
window.he.currentTime},yb:function(){return window.ve?1:0},nb:function(){return window.xe},t:Qb,d:Rb,Qa:Sb,W:Tb,e:Ub,Wa:Vb,Oa:Wb,L:Xb,sa:Yb,Q:Zb,ea:$b,V:ac,Pa:bc,b:dc,X:ec,Zc:fc,f:hc,Dd:jc,j:qc,Yd:tc,O:wc,h:xc,c:zc,a:Ac,id:Bc,g:Cc,da:Dc,ba:function(){return!window.he||window.he.paused||window.he.ended?0:1}};function od(a=[]){var b=ld;a.unshift(ba);var c=a.length,d=Ab((c+1)*4),e=d,g;for(g of a)u[e>>2]=Bb(g),e+=4;u[e>>2]=0;try{var f=b(c,d);ha=f;wa(f)}catch(l){va(l)}}
async function pd(){var a=aa;ia();var b=h.setStatus;b&&(b("Running..."),await new Promise(c=>setTimeout(c,1)),setTimeout(b,1,""));n||(qd._d(),h.onRuntimeInitialized?.(),h.noInitialRun||od(a),ka())}var qd;
(async function(){function a(d){d=qd=d.exports;ld=h._main=d.$d;M=d.be;Db=d.ce;Ab=d.de;Cb=d.ee;md=d.Zd;Jb=d.ae;d=md.buffer;U=new Int8Array(d);Fc=new Int16Array(d);q=new Uint8Array(d);uc=new Uint16Array(d);r=new Int32Array(d);u=new Uint32Array(d);V=new Float32Array(d);P=new Float64Array(d);ua=new BigInt64Array(d);new BigUint64Array(d);return qd}var b={a:nd},c=h.instantiateWasm;if(c)return new Promise(d=>{c(b,e=>d(a(e)))});na??=h.locateFile?h.locateFile("index.wasm",da):da+"index.wasm";return function(d){return a(d.instance)}(await qa(b))})().then(()=>
pd());
